services:
  jekyll:
    image: jekyll/jekyll:latest
    ports:
      - "8080:8080"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    command: jekyll serve --watch --force_polling --host 0.0.0.0 --port 8080 --livereload
