site_name: "Uendert Andrade"
site_url: https://uendert.github.io/
site_description: "Personal website of Uendert Andrade, a cosmologist working on DESI BAO, large-scale structure, and tests of dark energy and gravity."
site_author: "Uendert Andrade"
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  # icon:
  #   logo: fontawesome/solid/U
  logo: assets/eu.jpg
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.caret

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Uendert
    # - icon: fontawesome/brands/google-scholar
    #   link: https://scholar.google.com/citations?user=XXXX
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-4118-8236

copyright: Copyright &copy; 2025-2026 Uendert Andrade
extra_css:
  - assets/extra-20260524.css

nav:
  - Uendert Andrade: index.md
  - Research: research.md
  - Publications: publications.md
  - Talks: talks.md
  - CV: cv.md

# plugins:
#   - search
#   - bibtex:
#       # bib_file: "refs.bib"
#       bib_file: "export-bibtex.bib"
#       # csl_file: nature.csl
#       csl_file: apj.csl
      # bib_by_default: false
